language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: DEPLOY_FILE=wut-*.tar.bz2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:cginternals/backports-ppa'

cache:
  directories:
    - "$HOME/.local"
    - "/opt/devkitpro"

git:
  submodules: true

install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -O /tmp/devkitpro-pacman.deb
  - sudo dpkg -i /tmp/devkitpro-pacman.deb
  - yes | sudo dkp-pacman -Syu devkitPPC wut-tools
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITPPC=/opt/devkitpro/devkitPPC

script:
  - cd "$TRAVIS_BUILD_DIR"
  # Build wut
  - make -j4 install DESTDIR=wut_install
  - export WUT_ROOT=$PWD/wut_install
  - cd ../
  # Build tests
  - echo Tests disabled for now
#  - cd tests
#  - mkdir build && cd build
#  - cmake ../
#  - make -j4 VERBOSE=TRUE
#  - cd ../../
  # Build samples
  - cd samples/make
  - make -j4
  - cd ../../

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: gH3xndfXg4xCXUaqYvGecr9mzLXMMPOZfpqhnwuTIVnlAcR3jKeJ/3jlLs2Rm+GL1Mhby6f1YmtlhRX+G+OzDnp67m3kZaPsdZxqdn7SnBrVFEAbyv92wVullZB5O4mi7hYz5kAqFl0nzzfv7x5O1UtAqM3btFQAM4hiLDo2yqxsGCZsAsOlGCrwt6602hz0qnJ7PeOFAsxygdhdCmF+oWSzXVt0CZ1QfCZQzflZNO0M/CbYRtEcRE3iiHSWo6GRvMkTPw5o5Xca4cyuf1E86Aaym/ccwjKbrEIj77tImiH5iGhF7urXnjk2AxmpXHcDHSdB1WFLHdkbE7tdyhc11ahBJeOcof/LN3t/+HVqwjpse17kBBemc0y4pHyxSRZFoERQaP2mEvUMS1dVQXVdHm0RT3IKk7QBlRw0WTJX7sE836dhRenO03WyFgDRxNC6AT7DZsyN2UDEbOPFosBboiU73I3r8gvQtOKpMuDji6RPqUTUgEsB5HHXK1HLyijTAVbZPErNX97ucl6LdQ/uxmd/xgbZFc0jBUKa50H1/UN9LDlbw4Lf51Frl4rxg6DdZtDVx+6FTNaALm1iwAnVa7lhCDoH5Z+KVKJjKY1xW8P+OtTVFs1ZR/hkwblgc72hDShRyWkycYQTYgHwnRHL3OOObXDT6hZzggE5NwZJ8wg=
  file_glob: true
  file: $WUT_ROOT/$DEPLOY_FILE
  on:
    repo: devkitPro/wut
    tags: true
