name: Documentation

on:
  push:
  workflow_dispatch:

jobs:
  test-doc:
    name: Deploy documentation
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v2

    - name: Generate Documentation
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake doxygen doxygen-latex graphviz
        cd docs
        sudo env WUT_VERSION=${GITHUB_REF_NAME#v} cmake .
        doxygen Doxyfile.docs >/dev/null

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: docs/html
        single-commit: true
        clean: true
        clean-exclude: CNAME
